id: alien4cloud-kafka-listener
name: Kafka Listener
version: ${project.version}
description: >
  This plugin listens to a Kafka topic and performs requested actions
configuration_class: org.alien4cloud.plugin.kafka.listener.PluginConfiguration
component_descriptors:
  - bean_name: kafka-listener
    name: Kafka Listener
    description: >
      Alien Plugin that listens to a Kafka topic and performs requested actions
